### PR TITLE
readme: Fix link formatting

### PR DESCRIPTION
**Pull request by roman-mazur**
Change-type: patch
Signed-off-by: Roman Mazur <mazur.roman@gmail.com>

Also, closes #28

### CODE REVIEW

**Comment by roman-mazur** [comment]
Actually, duplicate of #28

**Comment by hedss** [comment]
Hi @roman-mazur ,

Thank you very much for the PR. There's a slight change required to the commit before our automated system will allow it. You need to add the following:

```
Change-type: patch
Signed-off-by: <githubHandle>
```

You can add a sign-off using `git commit -s`. This will allow our automated versioning system to verify the commit and update the appropriate files.

Thank you again!

**Comment by roman-mazur** [comment]
Thanks, will fix shortly.

**Comment by roman-mazur** [comment]
@hedss I fixed the commit message, though not sure what CI check results are not reported back

**Comment by dfunckt** [comment]
@resin-ci retest

**Comment by hedss** [comment]
Hi @roman-mazur,

Thanks, I think our CI was lagging slightly and hadn't caught up. All approved, and thanks again for the PR! :)

**Pull request merged**
